version: '3.8'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0  --port 8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
